### PR TITLE
fix: Minor change in testing.sh to download nltk data before running tests

### LINKED ISSUE #155: Fix small errors in PR template and some other errors to pass tests
## Description
As a developer,
I need to make small ammendments,
like fixing PR template and small changes to pass tests.

## Mocks
-N.A.-

### Update [Required]
- [ ] Fix PR templates and make other changes( in json, and test data, etc) 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by sammy1997**
### Description

Fixes #155

### Type of Change:
- Code
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
-N.A.-

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

File: testing.sh [hunk 1]
```diff
@@ -11,6 +11,6 @@ if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
     echo "Run tests only once( for the push )."
     exit 0
 fi
-
+python -m nltk.downloader -d /usr/share/nltk_data brown
```
Comment (sara-02) [inline testing.sh]: this command works for python2 but, I could not run it with Python3. I got this error 
```
/usr/bin/python3: Error while finding module specification for 'nltk.downloader' (ModuleNotFoundError: No module named 'nltk')
Can we have a more python version 2-3 compatible solution? Or for the time being, should, we just use this command and change this later while working on issue #.
```
Alteast we can add a comment saying `#works for python2 only`.

**Comment by sammy1997** [comment]
@sara-02 Please review and merge this! I will then send the PR for merging the work
